import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ReflectBackground from "./components/ReflectBackground";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative min-h-screen bg-black text-white overflow-hidden">
        <ReflectBackground
          backdropBlurAmount="md"
          className="fixed inset-0 z-0"
        />

        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}